lib{glaze}: {hxx}{**}

# Export options.
#
src_pfx = [dir_path] $src_root/include/

lib{glaze}:
{
  cxx.export.poptions = "-I$src_pfx"
}

# Install recreating subdirectories.
#
{hxx}{*}:
{
  install         = include/
  install.subdirs = true
}
