lib{glaze}: {hxx}{**}

# Export options.
#
src_pfx = [dir_path] $src_root/include/

lib{glaze}:
{
  cxx.export.poptions = "-I$src_pfx"
}

if ($cxx.target.system != 'win32-msvc')
{
  cxx.libs += -pthread
  lib{glaze}: cxx.export.libs += -pthread
}

# Install recreating subdirectories.
#
{hxx}{*}:
{
  install         = include/
  install.subdirs = true
}
