intf_libs =

if $config.libglaze.repe_rpc
  import intf_libs += libasio%lib{asio}

lib{glaze}: {hxx}{**} $intf_libs

# Export options.
#
src_pfx = [dir_path] $src_root/include/

lib{glaze}:
{
  cxx.export.poptions = "-I$src_pfx"
  cxx.export.libs = $intf_libs
}

if ($cxx.target.system != 'win32-msvc')
{
  cxx.libs += -pthread
  lib{glaze}: cxx.export.libs += -pthread
}

# Install recreating subdirectories.
#
{hxx}{*}:
{
  install         = include/
  install.subdirs = true
}
