intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
#import xxxx_libs += libhello%lib{hello}

sys_libs =
switch $cxx.target.system
{
  case 'freebsd'
  {
    sys_libs += \
      -ldl
  }
}

lib{glaze}: libul{glaze}: {hxx ixx txx cxx}{** -version} $impl_libs $intf_libs

# Build options.
#
cxx.libs += $sys_libs
cxx.poptions =+ "-I$out_root" "-I$src_base/include"

# Export options.
#
lib{glaze}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_base/include"
  cxx.export.libs = $intf_libs $sys_libs
}

# Export all symbols for windows (MSVC part)
libs{glaze}: def{glaze}: include = ($cxx.target.system == 'win32-msvc')
def{glaze}: libul{glaze}

if ($cxx.target.system == 'mingw32')
  cxx.loptions += -Wl,--export-all-symbols

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{glaze}: bin.lib.version = "-$version.project_id"
else
  lib{glaze}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libglaze/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
include/glaze/{hxx ixx txx}{**}:
{
  install         = include/glaze/
  install.subdirs = true
}
