import libs = libglaze%lib{glaze}

exe{driver}: {hxx cxx}{**} $libs

switch $cxx.id: path.match
{
  case 'gcc' | 'clang*'
  {
    cxx.coptions += -Wno-missing-braces
  }
  case 'msvc'
  {
    cxx.coptions += /Zc:preprocessor
  }
}
